Add support for Forwarded Authentication
ICTU/quality-time pull request #1559
Opened 2020-10-12 08:16 UTC by dicksnel

This feature adds support for Forwarded Authentication.

When Quality-Time is setup behind a reverse proxy that is responsible for authentication, an HTTP header such as `X-Forwarded-User` may be added to the request. If Forwarded Authentication is enabled and this header is present, Quality-Time will automatically login the user specified in the header.

**Security warning:** never enable Forwarded Authentication when Quality-Time is not behind a reverse proxy that is responsible for authentication.

2020-10-12 10:59 UTC, fniessink requested changes
Hi Dick,

The documentation needs updating as well:
- Deployment instructions (docs/DEPLOY.md)
- Changelog (docs/CHANGELOG.md)

2020-10-12 10:59 UTC, fniessink commented on components/server/src/routes/auth.py
> +    forward_auth_enabled = bool(os.environ.get("FORWARD_AUTH_ENABLED", None))
The None is not needed here because it's the default value of the "default" parameter of get().

2020-10-12 10:59 UTC, fniessink commented on components/server/tests/routes/test_auth.py
> +        """Test successful login from forwarded authentication header."""
This comment seems wrong (copy-paste error?).

2020-10-12 13:24 UTC, fniessink requested changes

2020-10-12 13:24 UTC, fniessink commented on docs/DEPLOY.md
> +
```suggestion
```

2020-10-12 13:24 UTC, fniessink commented on docs/DEPLOY.md
> +
These lines are a copy of lines 23-25.

2020-10-12 13:44 UTC, dicksnel commented on docs/DEPLOY.md
> +
Oops... :) fixed

2020-10-12 15:41 UTC, fniessink approved these changes

2020-10-12 15:51 UTC, fniessink commented
Please rebase on latest master so I can squash and merge.

2020-10-13 07:27 UTC, dicksnel commented
@fniessink I rebased on the latest master.

2020-10-13 07:29 UTC, merged