Issue 1645 investigate black
ICTU/quality-time pull request #1685
Opened 2020-11-19 16:37 UTC by emdv88

2020-11-19 16:44 UTC, emdv88 commented
Still need to take redo the black formatting after a rebase to prevent merge conflicts

also still have to include black in the developer manual

so not yet ready for merge

2020-11-19 18:12 UTC, emdv88 commented
Should be ready for merge now, except some newly introduced issues with sonarcloud, deepsource ant better code hub.
As far as I have checked they were all pre-existing issues that have now been picked up due to the core reformatting.

2020-11-19 22:56 UTC, emdv88 commented
now ready for a step by step introduction of black formatting. The git hook will only format python files that have been changed.

2020-11-20 10:51 UTC, fniessink requested changes

2020-11-20 10:51 UTC, fniessink commented on docs/DEVELOP.md
> +To automate autoformatting of python code using black, a git pre-commit hook is provided at `git-hooks/pre-commit`. To use it and automatically formal all changed python files on committing, copy thi
```suggestion
To enable autoformatting of Python code using black, a git pre-commit hook is provided at `git-hooks/pre-commit`. To use it and automatically format all changed Python files on committing, copy this script into your local `.git/hooks` folder of this repo.
```

2020-11-20 20:42 UTC, merged