1872 datamodel context
ICTU/quality-time pull request #2697
Opened 2021-10-07 13:31 UTC by emdv88

2021-10-07 14:39 UTC, fniessink requested changes

2021-10-07 14:39 UTC, fniessink commented on components/frontend/src/App.js
> +import { DataModel } from './context/Contexts';
Why is the file called `context/Contexts.js` when only the data model is in there and we also have a `context/Permissions.js`? Doesn't it make more sense to call the file `context/DataModel.js`?

2021-10-07 14:39 UTC, fniessink commented on components/frontend/src/metric/Metric.js
> +    const dataModel = useContext(DataModel)
No ";" at the end of the line. We should really introduce something like black for JS :-)

2021-10-07 14:39 UTC, fniessink commented on components/frontend/src/metric/Metric.js
> +    return source_statusses
```suggestion
    const sourceStatuses = sources.map(
        (source, index) => [index > 0 && ", ", <SourceStatus key={source.source_uuid} source_uuid={source.source_uuid} metric={metric} measurement_source={source} />]
    );
    return sourceStatuses
```

2021-10-07 14:39 UTC, fniessink commented on components/frontend/src/context/Contexts.js
> +export const DataModel = React.createContext(null);
```suggestion
export const DataModel = React.createContext(null);

```

2021-10-07 14:39 UTC, fniessink commented on components/frontend/src/trend_table/MeasurementsRow.js
> +import { useContext } from "react";
Hmm, interesting that we don't import React here and it still works.

2021-10-07 14:40 UTC, fniessink commented on components/frontend/src/metric/Metric.js
> +    const dataModel = useContext(DataModel)
But not as part of this PR of course.

2021-10-07 14:51 UTC, emdv88 commented on components/frontend/src/App.js
> +import { DataModel } from './context/Contexts';
True. I left the Permissions.js separate because it has it's own consumer component that is specified there. 
But the DataModel context is literally just a single line of code, so I think it doesn't make sense to create a file only for the DataModel. As it is currently I would define the DataModel Context in the App.js above the main class definition.

But finally, I think that it would be good to start using more context providers, for example for report, subject, metric, source, maybe more? so then it could make sense to put them all together in this Contexts.js file.

2021-10-07 14:53 UTC, emdv88 commented on components/frontend/src/metric/Metric.js
> +    const dataModel = useContext(DataModel)
I'm sure this is not the only spot. I think eslint can do something like that...

2021-10-07 14:56 UTC, emdv88 commented on components/frontend/src/trend_table/MeasurementsRow.js
> +import { useContext } from "react";
indeed it's kinda weird. I always thought that importing react was necessary if JSX is used in the file...

2021-10-08 15:37 UTC, fniessink commented on components/frontend/src/App.js
> +import { DataModel } from './context/Contexts';
Clear. Since we don't have any other context providers (yet), I've renamed Contexts.js to DataModel.js. We can always change it back.

2021-10-08 15:44 UTC, fniessink commented on components/frontend/src/metric/Metric.js
> +    const dataModel = useContext(DataModel)
I'll take a look.

2021-10-08 15:46 UTC, fniessink approved these changes

2021-10-13 20:53 UTC, merged