2692 latest measurements
ICTU/quality-time pull request #2747
Opened 2021-10-21 14:46 UTC by emdv88

2021-10-21 17:20 UTC, emdv88 commented
You'll see in the changes that I had to add a whole lot of wait seconds to the feature tests. This is because the get_latest_measurements_by_uuid will return the wrong latest measurement if the start time is the same (within the one second accuracy). This happened to accidentally go the right way in the old get_recent_measurements_by_uuid as long as the order in which they were inserted into the database was chronological. Maybe we should fix this "fallback" that the old method contained keeps working?

2021-10-24 15:31 UTC, fniessink requested changes

2021-10-24 15:31 UTC, fniessink commented on components/server/src/database/measurements.py
> +from typing import Dict, List
This isn't necessary anymore. You can use dict and list.
```suggestion
```

2021-10-24 15:31 UTC, fniessink commented on components/server/src/database/measurements.py
> +def latest_measurements_by_metric_uuid(database: Database, metric_uuids: List[str]) -> Dict[str, Measurement] | None:
```suggestion
def latest_measurements_by_metric_uuid(database: Database, metric_uuids: list[str]) -> dict[str, Measurement] | None:
```

2021-10-24 15:31 UTC, fniessink commented on components/server/src/database/measurements.py
> +    return latest_measurements_by_uuid
```suggestion
    return {measurement["metric_uuid"]: measurement for measurement in latest_measurements}
```

2021-10-24 15:31 UTC, fniessink commented on components/server/src/database/measurements.py
> +    )
This retrieves *all* measurements for the selected metric_uuids and then the dict comprehension on the next line keeps only the most recent one for each metric_uuid. That's not immediately obvious. And it retrieves much more data from the database than we need. Can't we make MongoDB do that work by passing a more restrictive filter?

For reports, we use a last flag. That's one way to solve this I guess. In that case, don't forget to update the index.

2021-10-24 15:31 UTC, fniessink commented on components/server/src/database/measurements.py
> +        filter_dict["metric_uuid"] = {"$in": metric_uuids}
```suggestion
    measurement_filter = {"end": {"$gte": min_iso_timestamp}, "start": {"$lte": max_iso_timestamp}}
    # metric_uuids needs to be optional as long as the /reports endpoint is supported for backwards compatibility
    # however, there is no test anymore covering that endpoint, which means incomplete coverage on this if statement
    if metric_uuids is not None:  # pragma: no cover
        measurement_filter["metric_uuid"] = {"$in": metric_uuids}
```

2021-10-24 15:31 UTC, fniessink commented on components/server/src/database/measurements.py
> +        filter_dict,
```suggestion
        measurement_filter,
```

2021-10-24 15:31 UTC, fniessink commented on components/server/src/model/transformations.py
> +
```suggestion
```

2021-10-24 15:31 UTC, fniessink commented on components/server/src/server_utilities/functions.py
> +def report_metrics_uuids(report: Dict) -> List[str]:
```suggestion
def report_metrics_uuids(report: dict) -> list[str]:
```

2021-10-24 15:31 UTC, fniessink commented on components/server/src/server_utilities/functions.py
> +from typing import Dict, List, Tuple, TypeVar, cast
```suggestion
from typing import Tuple, TypeVar, cast
```

(Tuple can be removed as well...)

2021-10-24 15:31 UTC, fniessink commented on components/server/tests/database/test_measurements.py
> +        def find_one_side_effect(query, projection=None, sort=None):  # pylint: disable=unused-argument
Why is the disable unused-argument needed? It looks like all three arguments are used.

2021-10-24 15:31 UTC, fniessink commented on components/server/tests/database/test_measurements.py
> +        """Test that we get all measurements with all metric id's."""
```suggestion
        """Test that we get all measurements with all metric ids."""
```

2021-10-24 15:31 UTC, fniessink commented on components/server/tests/database/test_measurements.py
> +        """Test that we get all measurements with all metric id's."""
```suggestion
        """Test that we get all measurements with all metric ids."""
```

2021-10-24 15:31 UTC, fniessink commented on components/server/tests/database/test_measurements.py
> +        """Test that we get all measurements with all metric id's."""
```suggestion
        """Test that we get all measurements with all metric ids."""
```

2021-10-24 15:31 UTC, fniessink commented on docs/src/changelog.md
> +- Add a parameter metric_uuids to recent_measurements_by_metric_uuid to minimize the database load. Closes [#2695](https://github.com/ICTU/quality-time/issues/2695).
As the changelog is mainly aimed at end users, I'm not sure it's useful to mention technical details like that here. On the other hand, it does make it easier for users to report bugs if they can relate buggy behavior to changes. So maybe:
```suggestion
- Performance improvements. Closes [#2692](https://github.com/ICTU/quality-time/issues/2692) and [#2695](https://github.com/ICTU/quality-time/issues/2695).
```

2021-10-27 14:15 UTC, fniessink commented on components/server/src/database/measurements.py
> +    latest_measurements_by_uuid = {measurement["metric_uuid"]: measurement for measurement in latest_measurements}
If multiple measurements for the same metric are within one second of each other, this does not return the most recent measurement.

2021-10-28 15:29 UTC, fniessink commented on components/server/src/database/measurements.py
> +            {"$group": {"_id": "$metric_uuid", "measurement_id": {"$first": "$_id"}}},
Is an alternative to copy all measurement fields (instead of just the measurement_id) as part of the `$group` step? Something like:
```suggestion
            {"$group": {"_id": "$metric_uuid", "metric_uuid": {"$first": "$metric_uuid"}, "sources": {"$first": "$sources"}, "start": {"$first": "$start"}, "end": {"$first": "$end"}, etc...},
```

That way the separate find isn't necessary and the result of the aggregation would basically be a list of measurements. A disadvantage of this approach is that the measurement fields need to be listed explicitly.

2021-10-28 16:41 UTC, merged