Support multiple LDAP servers
ICTU/quality-time pull request #4188
Opened 2022-07-14 12:04 UTC by wkoot

closes #4141

2022-07-14 15:21 UTC, fniessink requested changes

2022-07-14 15:21 UTC, fniessink commented on components/external_server/tests/routes/test_auth.py
> +            connection_mock.call_args_list[1][1], dict(user=self.USER_DN, password=PASSWORD, auto_bind='NO_TLS')
Line 30 is flagged by DeepSource as potentially insecure. Please add "  # skipcq: PY-A6006" to that line to suppress the DeepSource issue.

2022-07-15 08:28 UTC, emdv88 approved these changes

2022-07-15 12:08 UTC, fniessink requested changes
Forgot to mention with my previous review, please also add an entry to the change log (docs/src/changelog.md). 

Something this under "Added":

- Allow for configuring multiple LDAP servers to improve resilience. See the [deployment instructions](https://quality-time.readthedocs.io/en/latest/deployment.html) for more information on configuring LDAP. Closes [#4141](https://github.com/ICTU/quality-time/issues/4141).

2022-07-15 12:48 UTC, fniessink approved these changes

2022-07-15 12:48 UTC, merged