4747 better issue summary for issues created from quality time
ICTU/quality-time pull request #6112
Opened 2023-05-09 17:03 UTC by wkoot

2023-05-11 10:55 UTC, wkoot commented on docs/src/changelog.md
> +- Write a more descriptive issue summary and description for issues created from Quality-time. Closes [#4747](https://github.com/ICTU/quality-time/issues/4747).
Although the ticket lists adding an instruction to the manual, I think that https://quality-time.readthedocs.io/en/latest/usage.html#managing-technical-debt is already very descriptive. Listing more details in either changelog or docs will only make it more likely that they become outdated

2023-05-25 10:58 UTC, fniessink requested changes

2023-05-25 10:58 UTC, fniessink commented on components/external_server/src/routes/metric.py
> +    issue_summary, issue_description = create_issue_text(metric, last_measurement, data_model)
Can't we continue here with a (fake) measurement with an unknown value? That way the user can also create issues for metrics without measurements and we get rid of the if-statement. And get rid of the unit test `test_add_metric_issue_no_measurement` and the feature test `Creating a new issue for metric without measurements`.

2023-05-26 10:32 UTC, fniessink approved these changes

2023-05-26 11:18 UTC, merged