WIP
ICTU/quality-time pull request #6308
Opened 2023-06-08 19:56 UTC by wkoot

2023-06-15 12:36 UTC, fniessink requested changes

2023-06-15 12:36 UTC, fniessink commented on docs/src/changelog.md
> +- Add aXe analysis to Quality-time pipeline. Closes [#5402](https://github.com/ICTU/quality-time/issues/5402).
What's with the weird spelling? Axe writes axe as `axe` on their website.

```suggestion
- Add axe analysis to Quality-time pipeline. Closes [#5402](https://github.com/ICTU/quality-time/issues/5402).
```

2023-06-15 12:36 UTC, fniessink commented on tests/application_tests/src/test_report.py
> +        """Run aXe accessibility check on a report."""
```suggestion
        """Run axe accessibility check on a report."""
```

2023-06-15 12:36 UTC, fniessink commented on tests/application_tests/src/test_report.py
> +        # self.assertEqual(0, len(violation_results), readable_report)
Can we maybe add an assert that the number of violations is <= the current number of violations?

2023-06-15 18:35 UTC, wkoot commented on docs/src/changelog.md
> +- Add aXe analysis to Quality-time pipeline. Closes [#5402](https://github.com/ICTU/quality-time/issues/5402).
Huh, peculiar, I don't know how I picked this up

2023-06-16 13:06 UTC, fniessink approved these changes

2023-06-16 13:06 UTC, merged